### ISSUE TITLE
[Revise] Scalars are serialized during output. 

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/go-oscal#167]
### Environment
App version: v0.2.5

### Steps to reproduce
1. `make build`
2. download [tempo.yaml](https://raw.githubusercontent.com/defenseunicorns/compliance-artifacts/25b6e0c9140e807d61b3421b2362308a9b92ab00/tempo.yaml?token=GHSAT0AAAAAACML6KM4P6MBR4NT74QXLZXKZPQZOAA) and place in the go-oscal folder
3. run `./bin/gooscal revise -f tempo.yaml -o revised-tempo.yaml`
4. view diffs in the rego strings. 

### Visual Proof (screenshots, videos, text, etc)
This: 
```yaml
      - uuid: 335c291e-e847-47d5-a6bf-5cd0a7620292
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks: Allocate audit log storage capacity to accommodate organization-defined audit log retention requirements.
        description: >-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: persistentvolumeclaims
                  resourceRule:
                    Group: 
                    Version: v1
                    Resource: persistentvolumeclaims
                    Namespaces: [tempo]
                - name: storageclasses
                  resourceRule:
                    Group: storage.k8s.io
                    Version: v1
                    Resource: storageclasses
                    Namespaces: []
              rego: |
                package validate

                import future.keywords.every
                import future.keywords.in

                # Validate that the audit log storage capacity is sufficient to accommodate organization-defined audit log retention requirements.
                # For each storage class used in the pvc, check "allowVolumeExpansion: true" -> This is a property of the storage class
                validate {
                  every pvc in input.persistentvolumeclaims {
                    pvc.kind == "PersistentVolumeClaim"
                    storageClassName := pvc.spec.storageClassName

                    storageClass := findStorageClassByName(input.storageclasses, storageClassName)
                        storageClassValid(storageClass)
                  }
                }

                findStorageClassByName(sc, name) := i {
                  i := sc[_]
                    i.metadata.name == name
                }

                storageClassValid(sc) {
                  sc.allowVolumeExpansion == true
                }
```
becomes this: (deep equality, but serialized.)
```yaml
            - description: "target:\n  provider: opa\n  domain: kubernetes\n  payload:\n    resources:\n      - name: persistentvolumeclaims\n        resourceRule:\n          Group: \n          Version: v1\n          Resource: persistentvolumeclaims\n          Namespaces: [tempo]\n      - name: storageclasses\n        resourceRule:\n          Group: storage.k8s.io\n          Version: v1\n          Resource: storageclasses\n          Namespaces: []\n    rego: |\n      package validate\n\n      import future.keywords.every\n      import future.keywords.in\n\n      # Validate that the audit log storage capacity is sufficient to accommodate organization-defined audit log retention requirements.\n      # For each storage class used in the pvc, check \"allowVolumeExpansion: true\" -> This is a property of the storage class\n      validate {\n        every pvc in input.persistentvolumeclaims {\n          pvc.kind == \"PersistentVolumeClaim\"\n          storageClassName := pvc.spec.storageClassName\n\n          storageClass := findStorageClassByName(input.storageclasses, storageClassName)\n              storageClassValid(storageClass)\n        }\n      }\n\n      findStorageClassByName(sc, name) := i {\n        i := sc[_]\n          i.metadata.name == name\n      }\n\n      storageClassValid(sc) {\n        sc.allowVolumeExpansion == true\n      }"
              remarks: Allocate audit log storage capacity to accommodate organization-defined audit log retention requirements.
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: 335c291e-e847-47d5-a6bf-5cd0a7620292
```
### Next Steps
- look into removing trailing whitespace
- look into yaml linters that can be run against the incoming document if yaml.

**Comment by mike-winberry** [comment]
This seems to be a trailing whitespace issue, by removing all trailing whitespace from `tempo.yaml` I was able to solve the formatting issue
```yaml
# tempo.yaml
---
component-definition:
  uuid: 623DF5DB-52DD-4D9C-B4B9-6E1D9BA141A7
  metadata:
    title: Tempo Component
    last-modified: 2021-10-19T12:00:00Z
    version: "20211019"
    oscal-version: 1.1.1
    parties:
      - uuid: 72134592-08C2-4A77-ABAD-C880F109367A
        type: organization
        name: Platform One
        links:
          - href: https://p1.dso.mil
            rel: website
  components:
    - uuid: AE3E8F16-D93B-4594-82A3-5DA38AC066BF
      type: software
      title: Tempo
      description: >
        Grafana Tempo is an open source, easy-to-use, and high-scale
        distributed tracing backend
      purpose: Implementation of Observability
      responsible-roles:
        - role-id: provider
          party-uuids:
            - 72134592-08C2-4A77-ABAD-C880F109367A
      control-implementations:
        - uuid: d2afb4c4-2cd8-5305-a6cc-d1bc7b388d0c
          source: https://raw.githubusercontent.com/GSA/fedramp-automation/93ca0e20ff5e54fc04140613476fba80f08e3c7d/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json
          description: Controls implemented by Tempo for inheritance by applications
          implemented-requirements:
            - uuid: 3C102ED9-4CE5-4AB1-ABE5-78426DF15BBE
              control-id: au-4
              description: >-
                # Control Description
                  Organizations consider the types of auditing to be performed and the audit processing requirements when allocating audit storage capacity.
                  Allocating sufficient audit storage capacity reduces the likelihood of such capacity being exceeded and resulting in the potential loss or reduction of auditing capability.

                # Control Implementation
                  Uses scalable object storage to allocate audits logs.
              remarks:
                This control is partially implemented by this tool. "Partial"
                implementation specified due to the fact that the audit logs
                stored by this tool are a fraction of total audit logs that may
                be generated by the system. "Scalable object storage" here is
                interpretted to mean use of a storage class that allows for
                volume expansion.
              links:
                - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                  rel: reference
                  text: Lula Validation
                - href: 335c291e-e847-47d5-a6bf-5cd0a7620292
                  rel: reference
                  text: Lula Validation
            - uuid: 9904027A-28A8-4808-8617-D0DD29BF9B8B
              control-id: au-12.1
              description: >-
                # Control Description
                  Audit trails are time-correlated if the time stamps in the individual audit records can be reliably related to the time stamps in other audit records to achieve a time ordering of the records within organizational tolerances.
                  The information system compiles audit records from organization-defined information system components into a system-wide (logical or physical) audit trail that is time-correlated to within organization-defined level of tolerance for relationship between time stamps of individual records in the audit trail.

                # Control Implementation
                  Provides a time-series event compilation audit trail capabilities.
              remarks:
                This control is partially implemented by this tool. "Partial"
                implementation specified due to the fact that the audit logs
                stored by this tool are a fraction of total audit logs that may
                be generated by the system.
              links:
                - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                  rel: reference
                  text: Lula Validation
                - href: 7cc72008-5eac-45d7-aa75-57f78e236b92
                  rel: reference
                  text: Lula Validation
            - uuid: D0EE25CB-DAA8-4298-BBB9-A5AC72034020
              control-id: si-4.4
              description: >-
                # Control Description
                  Unusual/unauthorized activities or conditions related to information system inbound and outbound communications traffic include, for example,
                  internal traffic that indicates the presence of malicious code within organizational information systems or propagating among system components, the unauthorized exporting of information, or signaling to external information systems.
                  Evidence of malicious code is used to identify potentially compromised information systems or information system components.
                  The information system monitors inbound and outbound communications traffic organization-defined frequency for unusual or unauthorized activities or conditions.

                # Control Implementation
                  Tempo is used, in conjunction with Istio configurations, to collect and aggregate network communications within the system.
                  This allows the monitoring of inbound/outbound traffic and payloads within the deployed environment.
              remarks: This control is partially implemented by this tool.
              links:
                - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                  rel: reference
                  text: Lula Validation
                - href: 37698a15-7a0c-4145-ac80-d7a5cb501597
                  rel: reference
                  text: Lula Validation
                - href: 3a271aaa-75f5-4534-89da-8a39214f787f
                  rel: reference
                  text: Lula Validation
  back-matter:
    resources:
      - uuid: 0DA4FE66-9000-49DF-B896-938C94AAE89C
        title: Tempo
        rlinks:
          - href: https://grafana.com/oss/tempo/
      - uuid: 745E3948-04EE-40E4-9D6A-4F663342A031
        title: Big Bang Tempo package
        rlinks:
          - href: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/tempo
      - uuid: eac19387-6251-4d0e-ba2e-e90ec3963740
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks: Tempo healthcheck
        description: |-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: statefulsets
                  resourceRule:
                    Group: apps
                    Version: v1
                    Resource: statefulsets
                    Namespaces: [tempo]
              rego: |
                package validate
                import future.keywords.every
                import future.keywords.in

                # Readiness check on tempo pods
                validate {
                  every statefulset in input.statefulsets {
                    statefulset.kind == "StatefulSet"
                    podsRequired := statefulset.status.replicas
                    podsReady := statefulset.status.readyReplicas
                    podsReady == podsRequired
                  }
                }
      - uuid: 335c291e-e847-47d5-a6bf-5cd0a7620292
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks:
          Allocate audit log storage capacity to accommodate organization-defined
          audit log retention requirements.
        description: >-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: persistentvolumeclaims
                  resourceRule:
                    Group:
                    Version: v1
                    Resource: persistentvolumeclaims
                    Namespaces: [tempo]
                - name: storageclasses
                  resourceRule:
                    Group: storage.k8s.io
                    Version: v1
                    Resource: storageclasses
                    Namespaces: []
              rego: |
                package validate

                import future.keywords.every
                import future.keywords.in

                # Validate that the audit log storage capacity is sufficient to accommodate organization-defined audit log retention requirements.
                # For each storage class used in the pvc, check "allowVolumeExpansion: true" -> This is a property of the storage class
                validate {
                  every pvc in input.persistentvolumeclaims {
                    pvc.kind == "PersistentVolumeClaim"
                    storageClassName := pvc.spec.storageClassName

                    storageClass := findStorageClassByName(input.storageclasses, storageClassName)
                        storageClassValid(storageClass)
                  }
                }

                findStorageClassByName(sc, name) := i {
                  i := sc[_]
                    i.metadata.name == name
                }

                storageClassValid(sc) {
                  sc.allowVolumeExpansion == true
                }
      - uuid: 7cc72008-5eac-45d7-aa75-57f78e236b92
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks:
          Compile audit records from organization-defined system components into
          a system-wide (logical or physical) audit trail that is
          time-correlated to within organization-defined level of tolerance for
          the relationship between time stamps of individual records in the
          audit trail. Check that tempo dashboard service is available for audit
          log interrogation.
        description: >-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: temposvc
                  resourceRule:
                    Name: tempo-tempo
                    Group:
                    Version: v1
                    Resource: services
                    Namespaces: [tempo]
                - name: tempovs
                  resourceRule:
                    Name: tempo-query
                    Group: networking.istio.io
                    Version: v1alpha3
                    Resource: virtualservices
                    Namespaces: [tempo]
              rego: |
                package validate

                import future.keywords.every

                tempoSvc = input.temposvc
                tempoVs = input.tempovs

                validate {
                    # Existance of tempoSvc and tempoVs
                    tempoSvc.kind == "Service"
                    tempoVs.kind == "VirtualService"

                  # The virtual service should route to the tempo service
                  destinationPorts := [port | route := tempoVs.spec.http[_].route[_]; destination := route.destination; port := destination.port.number]
                  every port in destinationPorts {
                    service_provided_port(port)
                  }
                }

                service_provided_port(vsPort) {
                  # Check that some port is broadcasting on the expected virtual service port
                  port := tempoSvc.spec.ports[_]
                  port.targetPort == vsPort
                }
      - uuid: 37698a15-7a0c-4145-ac80-d7a5cb501597
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks: Monitor inbound and outbound communications traffic
          organization-defined frequency for organization-defined unusual or
          unauthorized activities or conditions - Check that all workloads have
          the Istio sidecar injected.
        description: >-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: pods
                  resourceRule:
                    Group:
                    Version: v1
                    Resource: pods
                    Namespaces: []
              rego: |
                package validate
                import future.keywords.every
                import future.keywords.in

                # Tracing is implemented via istio-proxy sidecar containers. Check that all workloads have the sidecar injected.
                # This function has been used before, good to identify how we can pull this out and reuse it.

                validate {
                  every pod in input.pods {
                    pod.kind == "Pod"
                    allowed_pod(pod)
                  }
                }

                allowed_pod(pod) {
                  images := pod.spec.containers[_].image
                  contains(images, "proxyv2")
                }

                allowed_pod(pod) {
                  exempt := {"kube-system", "istio-system", "istio-operator", "flux-system", "kyverno"}
                  pod.metadata.namespace in exempt
                }
      - uuid: 3a271aaa-75f5-4534-89da-8a39214f787f
        title: Lula Validation
        rlinks:
          - href: lula.dev
        remarks: Monitor inbound and outbound communications traffic
          organization-defined frequency for organization-defined unusual or
          unauthorized activities or conditions - Check that tempo is the
          configured tracing backend for the istio service mesh.
        description: >-
          target:
            provider: opa
            domain: kubernetes
            payload:
              resources:
                - name: istioconfigmap
                  resourceRule:
                    Name: istio
                    Group:
                    Version: v1
                    Resource: configmaps
                    Namespaces: [istio-system]
                - name: tempoconfigmap
                  resourceRule:
                    Name: tempo
                    Group:
                    Version: v1
                    Resource: configmaps
                    Namespaces: [tempo]
              rego: |
                package validate

                import future.keywords.in

                istioCm = input.istioconfigmap
                tempoCm = input.tempoconfigmap

                # Check istio configmap has "tempo" as the tracing backend and tempo configmap is configured to recieve traces from istio
                validate {
                  istioCm.kind == "ConfigMap"
                  tempoCm.kind == "ConfigMap"

                  # Check that the mesh config contains the substring "enableTracing: true"
                  # This would be better to parse the data for actual tracing field - e.g., mesh.defaultConfig.tracing.zipkin.address - TBD
                  contains(istioCm.data.mesh, "enableTracing: true")

                  # Check that the mesh config contains the substring "tempo-tempo.tempo.svc:9411" -> Address of the zipkin service
                  # This could also be any other kind of tracing backend that Istio supports, this particular implementation uses Zipkin
                  contains(istioCm.data.mesh, "tempo-tempo.tempo.svc:9411")

                  # Check that the tempo endpoint for zipkin matches the port from the service
                  # This is another imperfect one, the tempo config is tempo.yaml and the zipkin endpoint is distributer.receivers.zipkin.endpoint...
                  contains(tempoCm.data["tempo.yaml"], "endpoint: 0.0.0.0:9411")

                  # The proxy.istio.io/config annotation on a pod overrides the mesh settings - check if this overrides anything?
                  # Tracing typically doesn't grab every event, it looks like the config is to grab 100%.. should this be checked for compliance to this control as well?
                }
```
Now results in 
```yaml
# upgraded tempo.yaml
component-definition:
    back-matter:
        resources:
            - rlinks:
                - href: https://grafana.com/oss/tempo/
              title: Tempo
              uuid: 0DA4FE66-9000-49DF-B896-938C94AAE89C
            - rlinks:
                - href: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/tempo
              title: Big Bang Tempo package
              uuid: 745E3948-04EE-40E4-9D6A-4F663342A031
            - description: |-
                target:
                  provider: opa
                  domain: kubernetes
                  payload:
                    resources:
                      - name: statefulsets
                        resourceRule:
                          Group: apps
                          Version: v1
                          Resource: statefulsets
                          Namespaces: [tempo]
                    rego: |
                      package validate
                      import future.keywords.every
                      import future.keywords.in

                      # Readiness check on tempo pods
                      validate {
                        every statefulset in input.statefulsets {
                          statefulset.kind == "StatefulSet"
                          podsRequired := statefulset.status.replicas
                          podsReady := statefulset.status.readyReplicas
                          podsReady == podsRequired
                        }
                      }
              remarks: Tempo healthcheck
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: eac19387-6251-4d0e-ba2e-e90ec3963740
            - description: |-
                target:
                  provider: opa
                  domain: kubernetes
                  payload:
                    resources:
                      - name: persistentvolumeclaims
                        resourceRule:
                          Group:
                          Version: v1
                          Resource: persistentvolumeclaims
                          Namespaces: [tempo]
                      - name: storageclasses
                        resourceRule:
                          Group: storage.k8s.io
                          Version: v1
                          Resource: storageclasses
                          Namespaces: []
                    rego: |
                      package validate

                      import future.keywords.every
                      import future.keywords.in

                      # Validate that the audit log storage capacity is sufficient to accommodate organization-defined audit log retention requirements.
                      # For each storage class used in the pvc, check "allowVolumeExpansion: true" -> This is a property of the storage class
                      validate {
                        every pvc in input.persistentvolumeclaims {
                          pvc.kind == "PersistentVolumeClaim"
                          storageClassName := pvc.spec.storageClassName

                          storageClass := findStorageClassByName(input.storageclasses, storageClassName)
                              storageClassValid(storageClass)
                        }
                      }

                      findStorageClassByName(sc, name) := i {
                        i := sc[_]
                          i.metadata.name == name
                      }

                      storageClassValid(sc) {
                        sc.allowVolumeExpansion == true
                      }
              remarks: Allocate audit log storage capacity to accommodate organization-defined audit log retention requirements.
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: 335c291e-e847-47d5-a6bf-5cd0a7620292
            - description: |-
                target:
                  provider: opa
                  domain: kubernetes
                  payload:
                    resources:
                      - name: temposvc
                        resourceRule:
                          Name: tempo-tempo
                          Group:
                          Version: v1
                          Resource: services
                          Namespaces: [tempo]
                      - name: tempovs
                        resourceRule:
                          Name: tempo-query
                          Group: networking.istio.io
                          Version: v1alpha3
                          Resource: virtualservices
                          Namespaces: [tempo]
                    rego: |
                      package validate

                      import future.keywords.every

                      tempoSvc = input.temposvc
                      tempoVs = input.tempovs

                      validate {
                          # Existance of tempoSvc and tempoVs
                          tempoSvc.kind == "Service"
                          tempoVs.kind == "VirtualService"

                        # The virtual service should route to the tempo service
                        destinationPorts := [port | route := tempoVs.spec.http[_].route[_]; destination := route.destination; port := destination.port.number]
                        every port in destinationPorts {
                          service_provided_port(port)
                        }
                      }

                      service_provided_port(vsPort) {
                        # Check that some port is broadcasting on the expected virtual service port
                        port := tempoSvc.spec.ports[_]
                        port.targetPort == vsPort
                      }
              remarks: Compile audit records from organization-defined system components into a system-wide (logical or physical) audit trail that is time-correlated to within organization-defined level of tolerance for the relationship between time stamps of individual records in the audit trail. Check that tempo dashboard service is available for audit log interrogation.
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: 7cc72008-5eac-45d7-aa75-57f78e236b92
            - description: |-
                target:
                  provider: opa
                  domain: kubernetes
                  payload:
                    resources:
                      - name: pods
                        resourceRule:
                          Group:
                          Version: v1
                          Resource: pods
                          Namespaces: []
                    rego: |
                      package validate
                      import future.keywords.every
                      import future.keywords.in

                      # Tracing is implemented via istio-proxy sidecar containers. Check that all workloads have the sidecar injected.
                      # This function has been used before, good to identify how we can pull this out and reuse it.

                      validate {
                        every pod in input.pods {
                          pod.kind == "Pod"
                          allowed_pod(pod)
                        }
                      }

                      allowed_pod(pod) {
                        images := pod.spec.containers[_].image
                        contains(images, "proxyv2")
                      }

                      allowed_pod(pod) {
                        exempt := {"kube-system", "istio-system", "istio-operator", "flux-system", "kyverno"}
                        pod.metadata.namespace in exempt
                      }
              remarks: Monitor inbound and outbound communications traffic organization-defined frequency for organization-defined unusual or unauthorized activities or conditions - Check that all workloads have the Istio sidecar injected.
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: 37698a15-7a0c-4145-ac80-d7a5cb501597
            - description: |-
                target:
                  provider: opa
                  domain: kubernetes
                  payload:
                    resources:
                      - name: istioconfigmap
                        resourceRule:
                          Name: istio
                          Group:
                          Version: v1
                          Resource: configmaps
                          Namespaces: [istio-system]
                      - name: tempoconfigmap
                        resourceRule:
                          Name: tempo
                          Group:
                          Version: v1
                          Resource: configmaps
                          Namespaces: [tempo]
                    rego: |
                      package validate

                      import future.keywords.in

                      istioCm = input.istioconfigmap
                      tempoCm = input.tempoconfigmap

                      # Check istio configmap has "tempo" as the tracing backend and tempo configmap is configured to recieve traces from istio
                      validate {
                        istioCm.kind == "ConfigMap"
                        tempoCm.kind == "ConfigMap"

                        # Check that the mesh config contains the substring "enableTracing: true"
                        # This would be better to parse the data for actual tracing field - e.g., mesh.defaultConfig.tracing.zipkin.address - TBD
                        contains(istioCm.data.mesh, "enableTracing: true")

                        # Check that the mesh config contains the substring "tempo-tempo.tempo.svc:9411" -> Address of the zipkin service
                        # This could also be any other kind of tracing backend that Istio supports, this particular implementation uses Zipkin
                        contains(istioCm.data.mesh, "tempo-tempo.tempo.svc:9411")

                        # Check that the tempo endpoint for zipkin matches the port from the service
                        # This is another imperfect one, the tempo config is tempo.yaml and the zipkin endpoint is distributer.receivers.zipkin.endpoint...
                        contains(tempoCm.data["tempo.yaml"], "endpoint: 0.0.0.0:9411")

                        # The proxy.istio.io/config annotation on a pod overrides the mesh settings - check if this overrides anything?
                        # Tracing typically doesn't grab every event, it looks like the config is to grab 100%.. should this be checked for compliance to this control as well?
                      }
              remarks: Monitor inbound and outbound communications traffic organization-defined frequency for organization-defined unusual or unauthorized activities or conditions - Check that tempo is the configured tracing backend for the istio service mesh.
              rlinks:
                - href: lula.dev
              title: Lula Validation
              uuid: 3a271aaa-75f5-4534-89da-8a39214f787f
    components:
        - control-implementations:
            - description: Controls implemented by Tempo for inheritance by applications
              implemented-requirements:
                - control-id: au-4
                  description: |-
                    # Control Description
                      Organizations consider the types of auditing to be performed and the audit processing requirements when allocating audit storage capacity.
                      Allocating sufficient audit storage capacity reduces the likelihood of such capacity being exceeded and resulting in the potential loss or reduction of auditing capability.

                    # Control Implementation
                      Uses scalable object storage to allocate audits logs.
                  links:
                    - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                      rel: reference
                      text: Lula Validation
                    - href: 335c291e-e847-47d5-a6bf-5cd0a7620292
                      rel: reference
                      text: Lula Validation
                  remarks: This control is partially implemented by this tool. "Partial" implementation specified due to the fact that the audit logs stored by this tool are a fraction of total audit logs that may be generated by the system. "Scalable object storage" here is interpretted to mean use of a storage class that allows for volume expansion.
                  uuid: 3C102ED9-4CE5-4AB1-ABE5-78426DF15BBE
                - control-id: au-12.1
                  description: |-
                    # Control Description
                      Audit trails are time-correlated if the time stamps in the individual audit records can be reliably related to the time stamps in other audit records to achieve a time ordering of the records within organizational tolerances.
                      The information system compiles audit records from organization-defined information system components into a system-wide (logical or physical) audit trail that is time-correlated to within organization-defined level of tolerance for relationship between time stamps of individual records in the audit trail.

                    # Control Implementation
                      Provides a time-series event compilation audit trail capabilities.
                  links:
                    - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                      rel: reference
                      text: Lula Validation
                    - href: 7cc72008-5eac-45d7-aa75-57f78e236b92
                      rel: reference
                      text: Lula Validation
                  remarks: This control is partially implemented by this tool. "Partial" implementation specified due to the fact that the audit logs stored by this tool are a fraction of total audit logs that may be generated by the system.
                  uuid: 9904027A-28A8-4808-8617-D0DD29BF9B8B
                - control-id: si-4.4
                  description: |-
                    # Control Description
                      Unusual/unauthorized activities or conditions related to information system inbound and outbound communications traffic include, for example,
                      internal traffic that indicates the presence of malicious code within organizational information systems or propagating among system components, the unauthorized exporting of information, or signaling to external information systems.
                      Evidence of malicious code is used to identify potentially compromised information systems or information system components.
                      The information system monitors inbound and outbound communications traffic organization-defined frequency for unusual or unauthorized activities or conditions.

                    # Control Implementation
                      Tempo is used, in conjunction with Istio configurations, to collect and aggregate network communications within the system.
                      This allows the monitoring of inbound/outbound traffic and payloads within the deployed environment.
                  links:
                    - href: eac19387-6251-4d0e-ba2e-e90ec3963740
                      rel: reference
                      text: Lula Validation
                    - href: 37698a15-7a0c-4145-ac80-d7a5cb501597
                      rel: reference
                      text: Lula Validation
                    - href: 3a271aaa-75f5-4534-89da-8a39214f787f
                      rel: reference
                      text: Lula Validation
                  remarks: This control is partially implemented by this tool.
                  uuid: D0EE25CB-DAA8-4298-BBB9-A5AC72034020
              source: https://raw.githubusercontent.com/GSA/fedramp-automation/93ca0e20ff5e54fc04140613476fba80f08e3c7d/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json
              uuid: d2afb4c4-2cd8-5305-a6cc-d1bc7b388d0c
          description: |
            Grafana Tempo is an open source, easy-to-use, and high-scale distributed tracing backend
          purpose: Implementation of Observability
          responsible-roles:
            - party-uuids:
                - 72134592-08C2-4A77-ABAD-C880F109367A
              role-id: provider
          title: Tempo
          type: software
          uuid: AE3E8F16-D93B-4594-82A3-5DA38AC066BF
    metadata:
        last-modified: 2024-03-12T15:52:55.958241257-07:00
        oscal-version: 1.1.2
        parties:
            - links:
                - href: https://p1.dso.mil
                  rel: website
              name: Platform One
              type: organization
              uuid: 72134592-08C2-4A77-ABAD-C880F109367A
        title: Tempo Component
        version: "20211019"
    uuid: 623DF5DB-52DD-4D9C-B4B9-6E1D9BA141A7
```
