### ISSUE TITLE
Missing properties for non-required top-level keys

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#269]
### Steps to reproduce
1. Add an invalid field to `testdata/validation/valid-component-definition.yaml`
2. Execute `go-oscal validate -f testdata/validation/valid-component-definition.yaml -r output.yaml`
3. Review the errors

### Expected result
Single error for the invalid field

### Actual Result
```yaml
valid: false
timeStamp: 2024-06-18T15:59:49.449638313Z
errors:
    - keywordLocation: /oneOf/0/required
      absoluteKeywordLocation: http://csrc.nist.gov/ns/oscal/1.0/1.0.4/oscal-complete-schema.json#/oneOf/0/required
      instanceLocation: ""
      error: 'missing properties: ''catalog'', missing properties: ''profile'''
    - keywordLocation: /oneOf/2/properties/component-definition/$ref/properties/components/items/$ref/additionalProperties
      absoluteKeywordLocation: http://csrc.nist.gov/ns/oscal/1.0/1.0.4/oscal-complete-schema.json#/definitions/oscal-complete-oscal-component-definition:defined-component/additionalProperties
      instanceLocation: /component-definition/components/0
      error: additionalProperties 'test' not allowed
    - keywordLocation: /oneOf/3/required
      absoluteKeywordLocation: http://csrc.nist.gov/ns/oscal/1.0/1.0.4/oscal-complete-schema.json#/oneOf/3/required
      instanceLocation: ""
      error: 'missing properties: ''system-security-plan'', missing properties: ''assessment-plan'', missing properties: ''assessment-results'', missing properties: ''plan-of-action-and-milestones'''
metadata:
    documentPath: testdata/validation/valid-component-definition.yaml
    documentType: component-definition
    documentVersion: 1.0.4
    schemaVersion: 1.0.4
```

Note the two entries for `missing-properties` being the non-existent models.

### Severity/Priority
medium

### Additional Context
May be a byproduct of our use of the complete schema - when no invalid fields are present, the linting passes without any errors.
